spring:
  config:
    name: notification-persist-service

  data:
    mongodb:
      database: notification
      host: localhost
      port: 8083

  cache:
    type: redis
    redis:
      cacheNullValues: false
      timeToLive: 86400

  redis:
    host: localhost
    port: 8084
    timeout: 1000

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:8091

  cloud:
    stream:
      default:
        contentType:
      bindings:
        persist:
          destination: queue.persist
          group: notification-persist-service
        process:
          destination: queue.process
          group: notification-process-service
        render:
          destination: queue.render
          group: notification-render-service

  rabbitmq:
    host: localhost
    port: 8085
    password: guest
    username: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

server:
  port: 8101

management:
  endpoints:
    web:
      exposure:
        include: '*'
