spring:
  config:
    name: notification-deliver-service

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:8091

  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        deliver:
          destination: queue.deliver
          group: notification-deliver-service

  rabbitmq:
    host: localhost
    port: 8085
    password: guest
    username: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

server:
  port: 8120

management:
  endpoints:
    web:
      exposure:
        include: '*'
