global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'notification-config-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'notification-discovery-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'notification-process-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8100']

  - job_name: 'notification-persist-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8101']
